apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject
        image: ones1/myproject:latest  # Use the image you built and pushed to your registry
        ports:
        - containerPort: 8000  # Port your Django app listens on
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: myproject.settings
        # Add other environment variables as needed
