apiVersion: v1
kind: Service
metadata:
  name: myproject-service
spec:
  selector:
    app: myproject
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 8000  # Port your Django app listens on inside the container
  type: LoadBalancer  # Change to NodePort or ClusterIP as needed
