# Generated by Django 4.2.7 on 2024-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
