# Generated by Django 4.2.7 on 2024-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingsession',
            name='session_key',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
