# Generated by Django 4.2.7 on 2024-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shoppingsession_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
