# Generated by Django 4.2.7 on 2024-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_products_category_remove_products_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cateNameRussian',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productName',
        ),
        migrations.AddField(
            model_name='products',
            name='cateNameEng',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='cateNameRu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='productNameEng',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='productNameRu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
