# Generated by Django 4.2.7 on 2024-04-09 16:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_products_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_eng', models.CharField(default='', max_length=255)),
                ('product_name_ru', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(default='', max_length=7)),
                ('size', models.CharField(default='', max_length=10)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(upload_to='product_images/')),
                ('image_hover', models.ImageField(blank=True, upload_to='product_images/')),
                ('image_detail1', models.ImageField(blank=True, upload_to='product_images/')),
                ('image_detail2', models.ImageField(blank=True, upload_to='product_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='category',
            name='cate_name_eng',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='cate_name_ru',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
